sudo: required
services:
    - docker

before_install:
    - docker build -t r0b3rt24docker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true r0b3rt24docker/docker-react npm run test

language: generic